openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
servers:
  - url: https://wvolf3g561.execute-api.eu-west-1.amazonaws.com/prod
    description: Product Service
paths:
  /products:
    get:
      summary: Get list of products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        description: Product to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: integer
    NewProduct:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: integer
      required:
        - title
        - price
        - count
